[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsonwebtoken", "jwks-rsa", "pg", "cross-fetch"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[dev]
  publish = "public"
  functions = "functions"
  port = 8888

