[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "jose"]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  publish = "public"
  functions = "functions"
  port = 8888

